### ISSUE TITLE
question on file names

### ISSUE THREAD

**Issue by rthomazel** [leandrotk/advanced-typescript#1]
maybe rename `001.ts` to `destructuring.ts`

any reason to name the files numbers? just wondering :D

**Comment by imteekay** [comment]
At first, I created with numbers because I wanted to give a linear path to everyone that wanted to learn more about these types. But in the end, I didn't have a real linear path, it was more like a bunch of different files/types.

I updated the repo [with the naming](https://github.com/leandrotk/advanced-typescript/pull/4).

**Comment by rthomazel** [comment]
Nice, I think it's better this way. Easier to find what you're looking for ;D
